#############################################################################
# Makefile for building: leterrier-calculmental
# Generated by qmake (2.01a) (Qt 4.5.0) on: ven. juil. 16 12:42:45 2010
# Project:  leterrier-calculmental.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile leterrier-calculmental.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtScript -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		interface.cpp \
		exercice.cpp \
		baudruche.cpp \
		boutonspolygone.cpp moc_interface.cpp \
		moc_exercice.cpp \
		moc_baudruche.cpp \
		moc_boutonspolygone.cpp
OBJECTS       = main.o \
		interface.o \
		exercice.o \
		baudruche.o \
		boutonspolygone.o \
		moc_interface.o \
		moc_exercice.o \
		moc_baudruche.o \
		moc_boutonspolygone.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		leterrier-calculmental.pro
QMAKE_TARGET  = leterrier-calculmental
DESTDIR       = 
TARGET        = leterrier-calculmental

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_interface.h ui_exercice.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: leterrier-calculmental.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtScript.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile leterrier-calculmental.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtScript.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile leterrier-calculmental.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/leterrier-calculmental1.0.0 || $(MKDIR) .tmp/leterrier-calculmental1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/leterrier-calculmental1.0.0/ && $(COPY_FILE) --parents interface.h exercice.h baudruche.h boutonspolygone.h .tmp/leterrier-calculmental1.0.0/ && $(COPY_FILE) --parents main.cpp interface.cpp exercice.cpp baudruche.cpp boutonspolygone.cpp .tmp/leterrier-calculmental1.0.0/ && $(COPY_FILE) --parents interface.ui exercice.ui .tmp/leterrier-calculmental1.0.0/ && (cd `dirname .tmp/leterrier-calculmental1.0.0` && $(TAR) leterrier-calculmental1.0.0.tar leterrier-calculmental1.0.0 && $(COMPRESS) leterrier-calculmental1.0.0.tar) && $(MOVE) `dirname .tmp/leterrier-calculmental1.0.0`/leterrier-calculmental1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/leterrier-calculmental1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_interface.cpp moc_exercice.cpp moc_baudruche.cpp moc_boutonspolygone.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_interface.cpp moc_exercice.cpp moc_baudruche.cpp moc_boutonspolygone.cpp
moc_interface.cpp: interface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface.h -o moc_interface.cpp

moc_exercice.cpp: baudruche.h \
		exercice.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) exercice.h -o moc_exercice.cpp

moc_baudruche.cpp: baudruche.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) baudruche.h -o moc_baudruche.cpp

moc_boutonspolygone.cpp: boutonspolygone.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) boutonspolygone.h -o moc_boutonspolygone.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_interface.h ui_exercice.h
compiler_uic_clean:
	-$(DEL_FILE) ui_interface.h ui_exercice.h
ui_interface.h: interface.ui
	/usr/bin/uic-qt4 interface.ui -o ui_interface.h

ui_exercice.h: exercice.ui
	/usr/bin/uic-qt4 exercice.ui -o ui_exercice.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp interface.h \
		exercice.h \
		baudruche.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

interface.o: interface.cpp interface.h \
		ui_interface.h \
		exercice.h \
		baudruche.h \
		ui_exercice.h \
		boutonspolygone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interface.o interface.cpp

exercice.o: exercice.cpp exercice.h \
		baudruche.h \
		ui_exercice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exercice.o exercice.cpp

baudruche.o: baudruche.cpp baudruche.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baudruche.o baudruche.cpp

boutonspolygone.o: boutonspolygone.cpp boutonspolygone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boutonspolygone.o boutonspolygone.cpp

moc_interface.o: moc_interface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_interface.o moc_interface.cpp

moc_exercice.o: moc_exercice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exercice.o moc_exercice.cpp

moc_baudruche.o: moc_baudruche.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_baudruche.o moc_baudruche.cpp

moc_boutonspolygone.o: moc_boutonspolygone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boutonspolygone.o moc_boutonspolygone.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

