.TH leterrier-calcul-mental 1 "November 14, 2010"
.SH NAME
leterrier\-calcul\-mental \- a funny calculator
.SH SYNOPSIS
.B leterrier\-calcul\-mental
.SH DESCRIPTION
is a program which simulates a very strange calculator... Will you be able to master it ?
.PP

leterrier\-calcul\-mental (1)
.SH AUTHOR
This manual page and the script were written by Eric Seigne
<eric.seigne@ryxeo.com>.
